language: python
python: 3.9

before_script:
  - pip install gen3utils --upgrade

script:
  # validate manifest.json, etlMapping.yaml and gitops.json:
  - |
    # for push builds, TRAVIS_BRANCH is the current branch name; for PR
    # builds, it's the name of the branch targeted by the PR.
    # We need the latter, which we can't get for push builds, so the tests
    # only run properly on PRs.
    changed_files=$(git diff --name-only HEAD..$TRAVIS_BRANCH)
    envs=()
    for file in $changed_files; do
      envs+=($(echo "$file" | cut -d "/" -f1))
    done

    # remove duplicates
    envs=($(printf "%s\n" "${envs[@]}" | sort -u)); echo  "${uniq[@]}"
    echo "Updated: ${envs[@]}"

    PR_LABELS=$(curl -s "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/labels")
    if [[ $PR_LABELS == *"skip-gen3utils"* ]]; then
      echo "skipping gen3utils checks..."
      exit 0
    fi

    for dir in "${envs[@]}"; do
      echo " Validating $dir"
      man=$dir/manifest.json; etl=$dir/etlMapping.yaml; ptlcfg=$dir/portal/gitops.json;

      # validate manifest.json
      if [ -f $man ]; then
        gen3utils validate-manifest $man || exit 1
      fi

      # validate ETL mapping
      if [ -f $man ] && [ -f $etl ]; then
        gen3utils validate-etl-mapping $etl $man || exit 1
      fi

      # validate portal configuration
      if [ -f $man ] && [ -f $etl ] && [ -f $ptlcfg ]; then
        if [[ $TRAVIS_PULL_REQUEST != false ]]; then
          gen3utils validate-portal-config $etl $man $ptlcfg uc-cdis/cdis-manifest $TRAVIS_PULL_REQUEST || exit 1
        else
          gen3utils validate-portal-config $etl $man $ptlcfg || exit 1
        fi
      fi
    done

  # comment on PRs with relevant deployment changes:
  - if [[ $TRAVIS_PULL_REQUEST != false ]]; then gen3utils post-deployment-changes uc-cdis/cdis-manifest $TRAVIS_PULL_REQUEST; fi

env:
  global:
    # GITHUB_TOKEN
    secure: "AbcX9FfJOyjm1FL5aMGIjs3c6N6Yx8UkD9i/46y/EP+twX7AciYgt8PWQ1y2u/bxArroYZEYzuJjSJQ1rboLPnTrjlwO0Ay6HANgZ/My8Z6UWIScDqbx74Bdfx+ykXxyo6mnAO45gAcsdFGboyHBEZViGt7JECe5XiPAAJqJYNEus3M+lE+P8SD029ue53jrWWDXZBnm/gdZMN+DPTyJxnel/vI+1/i/zFKFPyMNZCZE2enVIov6k93uDruisVvzXxZsTjOqQJ5K+A47DUthBYXVkXwCTRvtfxEMD7J3Z0EtuBC44bD8ONoiD/F67Iirwzmj490ERnE5Tsg46/hqhyFbXnSn/SyGTLwNnHXjC57qSU5lLVT5SpWkmXptE8HLERUZ0ie9jR6ysFKSj+vGKuvkS+nNeYeFNZVS0YkSObfcq3VdiWabMJIcgRA7k6Tdamw5kV81zynG4tMGZEyRH2jNCJW07PAJqm97z6uKglAwpZSa1Q+iqJo6wU+cFcoBwllLRG4fLlUvtM97+QOodOOPON8020biyzrRCciPRaSp8SIqdSfybNm3rhsYdP7o3C0hQgDAue27dgmZCvdhazABa0BkKTzI/ALGLTlU7+a75KSbY1Tpt02K/YDCGYqI6E1LBFc36i/K9NPN8NtAKtvowkCb3Nf8oGIoMil3keo="
